### ISSUE TITLE
Schedule tab stage 5: run status

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/falcon#492]
@briandennis I'm just teeing up this issue for when Stage 3 is done... Stage 4 is basically all the stuff that's in your mock that's not in Stage 3, such as "last run time and status (Success/num-rows or failure)" and tags and force-run-right-now and so on.

**Comment by briandennis** [comment]
The aim with stage 4 is strictly to add in the ability to associate a name with queries. Note, our last [scope adjusted mocks](https://github.com/plotly/falcon-sql-client/issues/425#issuecomment-400813333) did not include the concepts of last run time, status, or tags.

**Comment by nicolaskruchten** [comment]
Ah ok we can rename this issue “stage 5” then :)
