### ISSUE TITLE
ERROR: Invalid string length on Linux

### ISSUE THREAD

**Issue by mikes-nasuni** [plotly/falcon#515]
When trying to query a MySQL Bugzilla DB from the Linux build, I can connect, but them an unable to perform any queries and simply see this error message on the screen: "ERROR: Invalid string length"

See Image: https://imgur.com/a/X4VKvyK

For what it's worth: Using the debug tools, I can see that the query request is completing successfully and returning the data, just not getting displayed to the table.

**Comment by n-riesco** [comment]
My guess would be that the table `attach_data` contains a column whose type [the mysql driver for node](https://github.com/mysqljs/mysql) can't parse.

**Comment by mikes-nasuni** [comment]
Is there an option or way to not perform that initial query by default?

**Comment by n-riesco** [comment]
No, there isn't. I guess that you're hitting issue #264 (we should've prioritised this issue :disappointed:). 

If you're familiar with building electron apps, as a temporary fix, you could edit [these lines](https://github.com/plotly/falcon/blob/fc38f2c42f77b4cc9723197816bd2d445731e140/app/constants/constants.js#L287-L296) and customise the initial query for mysql and build Falcon locally.

**Comment by mikes-nasuni** [comment]
Thanks, I was looking for this portion of the code when I opened the bug. If I feel adventurous, I'll try committing a pull request in the next few days. -- Feel free to dupe this bug to #264 if you want to keep things clean.

**Comment by n-riesco** [comment]
We have some instructions on how to build Falcon in https://github.com/plotly/falcon/blob/master/CONTRIBUTING.md but they really need updating.

The main point you need to be aware of is that Falcon can be built as an electron app or as a node backend. The instructions to build and run the electron app are:

```
yarn install
yarn rebuild:modules:electron
yarn build
yarn run
```

Feel free to open an issue if you need help building the app.

**Comment by n-riesco** [comment]
Closing in favour of #264.
